module.exports = {
    RESOURCE_CREATED: "RECURSO CREADO CON EXITO",
    RESOURCE_FOUND : "RECURSO ENCONTRADO CON EXITO",
    RESOURCE_EDITED: "RECURSO EDITADO CON EXITO",
    RESOURCE_DELETED: "RECURSO ELIMINADO CON EXITO",
    RESOURCES_FOUND: "RECURSOS LISTADOS CON EXITO",

    INTERNAL_ERROR : "ERROR INTERNO EN EL SERVIDOR",
    CREDENTIAL_ERROR : "ERROR EN LAS CREDENCIALES",
    PROCESS_FAILED: "ERROR EN EL PROCESO"
}